version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend
    stdin_open: true

  backend:
    build: ./backend
    ports:
      - 8000:80
    container_name: backend
